/**
 * IPC channel name constants.
 *
 * This module MUST have no imports other than (at most) type-only ones.
 * It is the one thing both the main-process handler module (ipc.ts) and
 * the sandboxed preload (preload.ts) are allowed to share a VALUE import
 * with.
 *
 * Why this file exists at all, rather than preload.ts importing
 * IPC_CHANNELS straight out of ipc.ts: esbuild bundles whatever a value
 * import actually pulls in. ipc.ts imports store.ts, which imports
 * node:fs and node:path -- real Node built-ins that a sandboxed preload
 * (main.ts sets `sandbox: true` on the BrowserWindow, and that stays on
 * purpose) cannot touch. A preload that transitively requires("node:fs")
 * throws before it reaches contextBridge.exposeInMainWorld, so
 * `window.meadowmark` never gets defined and the renderer sees nothing --
 * with no error anywhere near the code that actually looks wrong.
 *
 * Keep this file a leaf: no imports of any other local module, ever. If
 * you need to add something both sides share, it either belongs here (if
 * it's inert data like this) or it needs its own leaf module -- it must
 * NOT be added to ipc.ts and then imported from preload.ts.
 */

export const IPC_CHANNELS = {
  windowMinimize: 'window:minimize',
  windowMaximize: 'window:maximize',
  windowClose: 'window:close',
  windowMaximizedChanged: 'window:maximized-changed',
  loadGame: 'game:load',
  saveGame: 'game:save',
  loadSettings: 'settings:load',
  saveSettings: 'settings:save',
  settingsServiceLoad: 'settings-service:load',
  settingsServiceSet: 'settings-service:set',
  settingsServiceSetMany: 'settings-service:set-many',
  settingsServiceResetToDefault: 'settings-service:reset-to-default',
  settingsServiceResetAllToDefaults: 'settings-service:reset-all-to-defaults',
  schedulesList: 'schedules:list',
  schedulesReplace: 'schedules:replace',
  schedulesEffective: 'schedules:effective',
  logoListPresets: 'logo:list-presets',
  logoCurrent: 'logo:current',
  logoApplyPreset: 'logo:apply-preset',
  logoApplyCustom: 'logo:apply-custom',
  logoReadAsset: 'logo:read-asset',
  logoReset: 'logo:reset',
  converterListCatalog: 'converter:list-catalog',
  converterListCategory: 'converter:list-category',
  converterSearchCatalog: 'converter:search-catalog',
  converterPickSource: 'converter:pick-source',
  converterDetect: 'converter:detect',
  converterConvert: 'converter:convert',
  converterExtract: 'converter:extract',
  exportsPreview: 'exports:preview',
  exportsLossReport: 'exports:loss-report',
  exportsSave: 'exports:save',
  ollamaDiagnose: 'ollama:diagnose',
  ollamaListInstalled: 'ollama:list-installed',
  ollamaListRunning: 'ollama:list-running',
  ollamaShowCapabilities: 'ollama:show-capabilities',
  ollamaRefreshCatalog: 'ollama:refresh-catalog',
  ollamaCatalogState: 'ollama:catalog-state',
  ollamaDetectHardware: 'ollama:detect-hardware',
  ollamaEvaluateFit: 'ollama:evaluate-fit',
  ollamaPullList: 'ollama:pull-list',
  ollamaPullCreate: 'ollama:pull-create',
  ollamaPullRun: 'ollama:pull-run',
  ollamaPullCancel: 'ollama:pull-cancel',
  ollamaChatList: 'ollama:chat-list',
  ollamaChatGet: 'ollama:chat-get',
  ollamaChatCreate: 'ollama:chat-create',
  ollamaChatRename: 'ollama:chat-rename',
  ollamaChatUpdateSystemPrompt: 'ollama:chat-update-system-prompt',
  ollamaChatUpdateParams: 'ollama:chat-update-params',
  ollamaChatDelete: 'ollama:chat-delete',
  ollamaChatSend: 'ollama:chat-send',
  ollamaChatRetry: 'ollama:chat-retry',
  ollamaChatStop: 'ollama:chat-stop',
  ollamaChatExportRedacted: 'ollama:chat-export-redacted',
  narratorLoadSettings: 'narrator:load-settings',
  narratorUpdateSettings: 'narrator:update-settings',
  narratorNarrate: 'narrator:narrate',
  narratorStatus: 'narrator:status',
  narratorEngineRequest: 'narrator-engine:request',
  narratorEngineRespond: 'narrator-engine:respond',
  vocabularyLoad: 'vocabulary:load',
  vocabularyState: 'vocabulary:state',
  vocabularyClear: 'vocabulary:clear',
  vocabularyResolve: 'vocabulary:resolve',
  authVaultAvailable: 'auth:vault-available',
  authClockStatus: 'auth:clock-status',
  authAcknowledgeClockJump: 'auth:acknowledge-clock-jump',
  authBeginRegistration: 'auth:begin-registration',
  authBeginRegistrationFromSecret: 'auth:begin-registration-from-secret',
  authBeginRegistrationFromUri: 'auth:begin-registration-from-uri',
  authPendingRegistration: 'auth:pending-registration',
  authCancelRegistration: 'auth:cancel-registration',
  authConfirmRegistration: 'auth:confirm-registration',
  authListEntries: 'auth:list-entries',
  authListGroups: 'auth:list-groups',
  authRenameEntry: 'auth:rename-entry',
  authRemoveEntry: 'auth:remove-entry',
  authCreateGroup: 'auth:create-group',
  authRenameGroup: 'auth:rename-group',
  authRemoveGroup: 'auth:remove-group',
  authCurrentCode: 'auth:current-code',
  locksList: 'locks:list',
  locksCreate: 'locks:create',
  locksChangeCredential: 'locks:change-credential',
  locksSetUnlockDuration: 'locks:set-unlock-duration',
  locksRemove: 'locks:remove',
  locksAttemptUnlock: 'locks:attempt-unlock',
  locksRelock: 'locks:relock',
  locksIsUnlocked: 'locks:is-unlocked',
  historyAvailability: 'history:availability',
  historyRecords: 'history:records',
  historyRevisions: 'history:revisions',
  historyDiff: 'history:diff',
  historyRestore: 'history:restore',
  historyLabel: 'history:label',
  historyPrune: 'history:prune',
  historyExportRedacted: 'history:export-redacted',
  updaterState: 'updater:state',
  updaterCheck: 'updater:check',
  updaterCancel: 'updater:cancel',
  updaterDismiss: 'updater:dismiss',
  updaterApply: 'updater:apply',
  updaterStateChanged: 'updater:state-changed',
  runtimeStatus: 'runtime:status',
  runtimeStatusChanged: 'runtime:status-changed',
  appInfo: 'app:info',
  historyInit: 'history:init',
  historyListRevisions: 'history:list-revisions',
  historyListRecords: 'history:list-records',
  historyDiffRevisions: 'history:diff-revisions',
  historyRestoreRevision: 'history:restore-revision',
  historyLabelRevision: 'history:label-revision',
  historyExport: 'history:export',
} as const;
